### ISSUE TITLE
Crackling audio; Windows 8.1

### ISSUE THREAD

**Issue by AquaBlackChan** [thestr4ng3r/chiaki#364] opened 2020-11-07 19:05 UTC
**Specs** 
- OS/Distribution: Windows / Windows 8.1
 - Hardware: Intel(R) HD Graphics Family
 - Exact Version or Commit Hash and Installation Method: v.1.3.0 _(is this how you do it?)_

**Describe the bug**
The bug is choppy audio whenever you get your PS4 screen onto your laptop.  

**To Reproduce**
There are no steps to get this.  It's been acting like this for quite sometime now.

**Expected behavior**
I don't... know what this is asking.  This is just crackling audio.

**Log Files**
There is no log files for this glitch.  It's an audio issue.

**Screenshots**
Not screenshots, but a video in case if you are wondering.
https://www.youtube.com/watch?v=1KE1LLwSoXQ&feature=youtu.be

**Additional context**
I already know that there are multiple questions about choppy audio, but I haven't been able to figure out my problem.  I've been trying to play Genshin Impact on my computer via PS4, but each time that I tried to get my screen onto my laptop, it would cause a horrific distortion noise.  I tried everything I could.

**I tried deleting the audio files; it worked, but I couldn't get it back.**
**I also tried lowering the volume through Genshin Impact and my system volume; didn't work either.**
One other thing I tried was that I also tried messing with the bitrate, graphics, etc.  Nothing worked.

It's not my WiFi either, as if it was, the quality would be dropping nonstop, and thankfully it hasn't.

Would anyone know that this is a soundcard issue, or is it because my laptop sucks like arse? Thanks a lot.

**Comment by thestr4ng3r** [comment] 2020-11-08 09:26
Duplicate of #1. Since this one isn't resolved yet, more issues wouldn't help.

**Closed by thestr4ng3r** 2020-11-08 09:26 UTC
