### ISSUE TITLE
Registration fails with HTTP code 403

### ISSUE THREAD

**Issue by ShinKaz** [thestr4ng3r/chiaki#6] opened 2019-08-21 09:05 UTC
getting 
```
[I] Regist starting search
[I] Regist sending search packet
[I] Regist received search response from 192.168.1.12
[I] Regist connected to 192.168.1.12, sending request
[I] Regist waiting for response
[E] Regist received HTTP code 403
[E] Regist eventually failed
```
on windows10.

(did open win10 firewall)

"An error has occured. (CE-35406-8)" on PS4 pro

everything on local network, ethernet wired.

thanks for you work ! really looking forward to an android port to play on switch ^^

**Comment by thestr4ng3r** [comment] 2019-08-21 09:20
Can you please enable verbose logging in the settings and post the output again? Also double-check that you entered the correct PSN ID and PIN otherwise registration will always fail.

**Comment by thestr4ng3r** [comment] 2019-08-21 09:28
Oh and if the registration succeeds, don't post the verbose log here, it would contain your authentication keys then.

**Comment by ShinKaz** [comment] 2019-08-21 12:31
well...it worked this time all I did since before :
tried to use the official PS4 remote play app first (had to update it, then got "connection with the server has expired" when trying to log my psn account. never worked.)

tried using your app, ticked the log option, started and it worked lol


is there anyway to use fullscreen ?

I did set quality to 1080@60, bu the quality isn't great. (I'm on gigabit ethernet  PS4 Pro<->router<->PC... (got a 1Gbps optic fiber connection but that souldn't matter since I'm over LAN here)
![image](https://user-images.githubusercontent.com/6830318/63431913-44931c00-c420-11e9-84b1-329093360336.png)

**Comment by thestr4ng3r** [comment] 2019-08-21 12:36
Ok, then I assume it was just a typo. Unfortunately the PS4 doesn't give us good error messages in case of registration failure, only the HTTP code.

The bitrate is too low currently, but that is already fixed on master and will be better in the next release (which will happen tonight probably). Error concealment would only kick in when frames can not be reconstructed with FEC, which should in practice almost never happen on a stable connection.

**Closed by thestr4ng3r** 2019-08-21 12:36 UTC

**Comment by ShinKaz** [comment] 2019-08-21 12:38
cool thanks ! will try it too :)

(honestly wasn't a typo, I used like 10 PIN codes and the same PSN ID and IP adress ;) )

**Comment by thestr4ng3r** [comment] 2019-08-21 12:42
Hm ok, then I will at least keep an eye out if I experience any registration issues in the future.

Have fun playing Tetris Effect!

**Comment by thestr4ng3r** [comment] 2019-08-21 12:50
Issue for Fullscreen: #9

**Comment by ShinKaz** [comment] 2019-08-21 17:10
> Hm ok, then I will at least keep an eye out if I experience any registration issues in the future.
> 
> Have fun playing Tetris Effect!

hehe, thanks ^^

**Comment by ShinKaz** [comment] 2019-08-21 17:50
Tried the new version and it works well and look much nicer :)

what metric is bitrate in ? (left it on automatic for now)

played some tetris effect and DragonBallFighterZ, is DBFZ I noticed that sometimes "dpad left" got stuck for like 5sec. (I'm new to using remote play (really started using it since android on switch) so this might be normal behavior/same behavior as the official app ?)

**Comment by thestr4ng3r** [comment] 2019-08-21 19:03
Bitrate is in kbps, but it might not directly represent the final video bitrate. It's a value called `bwKbpsSent` that the client reports to the console and the PS4 then decides how to encode the video.

Stuck buttons should only rarely happen on a stable connection, but by design of the protocol, it could theoretically occur on a packet drop and the button can stay stuck until the next button event. So not 100% sure if it's because of a bug or network in your case.

Android and Switch (native) is planned with Android being first probably. The entire library is written with portability in mind.

**Comment by ShinKaz** [comment] 2019-08-21 20:24
oh I see, 10000Kbps isn't that much for a local Gbit network, I'll try 50Mbps and see if it changes anything :)

yeah, that's weird because it happened a lot in a short time, and pressing the opposite direction wouldn't change much of anything for like 5 secs.

Sounds great! looking forward to it :)
