### ISSUE TITLE
Chiakia keeps crashing my computer

### ISSUE THREAD

**Issue by Darthelik** [thestr4ng3r/chiaki#282] opened 2020-07-18 20:56 UTC
My computer completely locks up after anywhere from 2 to 3 hours of game play when it happens i have to completely reboot my whole system and then log in again and this just keeps repeating im on OS: Manjaro KDE and it have also happened to me on OS: PoP os

**Comment by thestr4ng3r** [comment] 2020-07-20 12:17
Issue template ignored and duplicate of #273

**Closed by thestr4ng3r** 2020-07-20 12:17 UTC
