### ISSUE TITLE
Offline/LAN connection

### ISSUE THREAD

**Issue by TheRogueGrunt** [thestr4ng3r/chiaki#327] opened 2020-10-13 06:07 UTC
**What platform does your feature request apply to?**
Desktop, specifically Linux but Windows and MacOS would be nice.

**Is your feature request related to a problem? Please describe.**
I've been using this as an alternative to my capture card that doesn't work on Linux while streaming and would like to minimize the amount of bandwidth being used by anything that isn't the Twitch stream.

**Describe the solution you'd like**
Something akin to MysteryDash's Offline PS4 Remote Play patch, which unfortunately is only for the official Remote Play program and therefore lacking a Linux client.

**Describe alternatives you've considered**
Direct connecting my PS4 Pro to my PC via a 2nd Ethernet port and bridging the connections. (It didn't work.)

**Additional context**
MysteryDash's Offline Remote Play patch:
https://github.com/MysteryDash/Offline-PS4-Remote-Play

**Comment by thestr4ng3r** [comment] 2020-10-13 06:48
Chiaki doesn't require an Internet connection at all. Is there any particular issue you have using it on LAN?

**Comment by TheRogueGrunt** [comment] 2020-10-13 19:29
Occational visual gitches and artifacts as if the bitrate is too low

**Comment by thestr4ng3r** [comment] 2020-10-18 15:42
Well a few artifacts are not uncommon due to the low-latency nature of the protocol and most likely caused by the network conditions. If you are connecting over WLAN, try Ethernet instead, this can make a huge difference. You may also want to check out #292. I'll close this since the original request was about offline connection, which is already supported. If you come across any other concrete bug, feel free to open a new issue.

**Closed by thestr4ng3r** 2020-10-18 15:42 UTC
