### ISSUE TITLE
Multiple Profiles

### ISSUE THREAD

**Issue by ya-boop** [thestr4ng3r/chiaki#252] opened 2020-06-02 13:35 UTC
**What platform does your feature request apply to?**
Choose one or more: all

**Is your feature request related to a problem? Please describe.**
there is people with multiple accounts. eg one in PSN US/EU and second for PSN JAP. switching them with chiaki is problematic. because program overwrites previous account information

**Describe the solution you'd like**
ability to store and use all accounts without overwriting them.

**Comment by thestr4ng3r** [comment] 2020-06-02 16:47
Duplicate of #21

**Closed by thestr4ng3r** 2020-06-02 16:47 UTC
