### ISSUE TITLE
need microphone support

### ISSUE THREAD

**Issue by independentcod** [thestr4ng3r/chiaki#231] opened 2020-05-14 14:36 UTC
**What platform does your feature request apply to?**
Choose one or more: Desktop/Android/Both/...
arch linux laptop

**Is your feature request related to a problem? Please describe.**
Need microphone feature
**Describe the solution you'd like**
be able to talk in game
**Describe alternatives you've considered**
plugging my mic into controller
**Additional context**

**Comment by thestr4ng3r** [comment] 2020-05-14 14:58
Duplicate of #52

**Closed by thestr4ng3r** 2020-05-14 14:58 UTC
