### ISSUE TITLE
Chiaki on PS5 on linux

### ISSUE THREAD

**Issue by tausciam** [thestr4ng3r/chiaki#371] opened 2020-11-13 14:00 UTC
**Environment**
 - OS/Distribution: Arch Linux
 - Desktop Environment: KDE Plasma on X
 - Hardware: VmWare Player but also bare metal on Ryzen 5 3600, GTX 1060 6GB
 - Exact Version or Commit Hash and Installation Method: 1.3.0 AppImage

**Describe the bug**
Chiaki doesn't see or connect to the PS5

**To Reproduce**
I manually add the PS5 via IP address on the main screen. I add my PSN acct id I got from the python script. I used it on my former PS4 Pro so I know it's correct. Remote Play was enabled. I set to link device and put the PIN it gives me into Chiaki.

**Expected behavior**
Should connect, but search fails

**Log Files**
No log file is generated in $HOME/.local/share/Chiaki/Chiaki/log even though the folder is there. The terminal output is as follows:

[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed

**Additional context**
I would be happy to follow up with you and test patched versions or whatever.

**Comment by thestr4ng3r** [comment] 2020-11-13 14:43
Duplicate of #370

**Closed by thestr4ng3r** 2020-11-13 14:43 UTC
