### ISSUE TITLE
Registration Fails After Playstation System Update To Version 8.0.0 | Error (RP-Version mismatch)

### ISSUE THREAD

**Issue by Skor41on** [thestr4ng3r/chiaki#329] opened 2020-10-16 08:32 UTC
**Environment**
 - ***OS/Distribution:*** Manjaro Linux 
 - ***Desktop Environment:*** KDE Plasma Version 5.19.5 
- ***Hardware:***
```
CPU: Quad Core Intel Core i7-4700MQ.
Graphics: 
Device-1: Intel 4th Gen Core Processor Integrated Graphics with i915 driver
Device-2: NVIDIA GK208M [GeForce GT 740M] with nouveau driver.
Network: 
Device-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter with ath9k driver
Device-2: Qualcomm Atheros QCA8171 Gigabit Ethernet with alx driver
```
- ***Exact Version or Commit Hash and Installation Method:*** 
```
Package Version: 1.2.1.r37.gf1071f3 
Build Method: built through pacman package manager
```

**Describe the bug**
I can't register my ps4 after the last update from playstation `version 8.0.0` on `14/10/2020`, i tried numerous solutions but none of them worked.
Everytime i try registering my device I get error `Reported Application Reason: 0x80108b11 (RP-Version mismatch)`, so help please.
Note: i tried the app on windows as well, produces the same issue.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Register New and insert relevant information'
![image](https://user-images.githubusercontent.com/72963129/96234539-27c68a00-0fcc-11eb-97ac-c5f1c2361561.png)
3. Click on 'Register'
![image](https://user-images.githubusercontent.com/72963129/96234009-6e67b480-0fcb-11eb-99e0-cfcf10ce3219.png)

**Expected behavior**
My ps4 should be registered successfully and i should see the stream on my laptop.

**Log Files**
I checked the directory, there's no file, i have the verbose logs though but they're required explicitly.

**Comment by thestr4ng3r** [comment] 2020-10-16 08:54
duplicate of #328

**Closed by thestr4ng3r** 2020-10-16 08:54 UTC

**Comment by genyg** [comment] 2020-10-16 11:56
Good afternoon. When will they fix it?
