### ISSUE TITLE
Keep screen on

### ISSUE THREAD

**Issue by shizet1** [thestr4ng3r/chiaki#137] opened 2020-01-08 20:28 UTC
I dont want to bother again but i wanted to try some gaming and my phone keeps getting to sleep. Is there an obvious option im missing again? Or is that a bug?

**Comment by thestr4ng3r** [comment] 2020-01-09 08:26
Duplicate of #114.
Unfortunately for now the only way is to change your phone's global settings, but it should be easy to fix.

**Closed by thestr4ng3r** 2020-01-09 08:26 UTC
Labels: question
