### ISSUE TITLE
extremely slow performance on OpesSuse Linux

### ISSUE THREAD

**Issue by kivarun** [thestr4ng3r/chiaki#190] opened 2020-03-16 14:41 UTC
I tried chiaki connected to PS4Pro on my Laptop with OpesSuse 15.1 Linux installed.
Performance is extremely slow, around 2-3 pps.

**Comment by lsiudut** [comment] 2020-04-22 19:36
Check if you have hardware acceleration enabled. Seems like OpenGL performance issues.

**Comment by thestr4ng3r** [comment] 2020-04-23 12:31
Most likely duplicate of #32

**Closed by thestr4ng3r** 2020-04-23 12:31 UTC

**Comment by kivarun** [comment] 2020-04-24 11:38
OpenGL is configured and working fine 
```glxinfo | grep render 
direct rendering: Yes
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (BDW GT2)
```
